---
#apiVersion: apps/v1
apiVersion: extensions/v1
#apiVersion: extensions/v1beta1 #as per https://plugins.jenkins.io/kubernetes-cd/   apiVersion: extensions/v1
#apiVersion: apps/v1beta1 # done for K8S version > 1.16
kind: Deployment
metadata:
  name: railwaytt-k8s-deployment
spec:
  selector:
    matchLabels:
      app: railwaytt
  replicas: 1 # deployment runs 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: railwaytt
    spec:
      containers:
      - name: railwaytt
        image: sagargupta03/railwaytt:latest
        ports:
        - containerPort: 80 #Endpoint is at port 80 in the container
---
apiVersion: v1
kind: Service
metadata:
  name: railwaytt-k8s-service
spec:
  type: NodePort #Exposes the service as a node port 
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 33081
  selector:
    app: railwaytt

