---
apiVersion: v1
kind: Service
metadata:
  name: railwaytt-k8s-service
spec:
  type: NodePort #Exposes the service as a node port 
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 33081
  selector:
    app: railwaytt
